build:
  stage: build
  tags:
    - shell
  script:
    - docker build --pull -t "docker-registry.beta.innovation.insee.eu/sl7cob/odil" .
    - docker push "docker-registry.beta.innovation.insee.eu/sl7cob/odil"
    
deploy:
  stage: deploy
  tags:
    - shell
  script:
    - 'APP_ID=`cat marathon.json | jq .id -r`'
    - 'curl -d@marathon.json -H "Content-Type: application/json" -X PUT http://marathon.mesos:8080/v2/apps/$APP_ID?force=true'
    - 'curl -X POST http://marathon.mesos:8080/v2/apps/$APP_ID/restart?force=true'
